name: Scheduled Health Check

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Configure Git for Automated Commits
        run: |
          git config --global user.name "${{ secrets.user_name }}"
          git config --global user.email "${{ secrets.user_email }}"
          git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Run Health Check Script
        id: shell_script_run
        run: bash ./scripts/health-check.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          user_name: ${{ secrets.user_name }}
          user_email: ${{ secrets.user_email }}