name: Scheduled Health Check

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Ensure the token with write permissions is used for checkout
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Configure GitHub Token
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./scripts/health-check.sh
