name: Scheduled Health Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up SSH key for pushing to GitHub
      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      # Step 3: Add GitHub to known hosts
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Step 4: Set up Git for committing
      - name: Set up Git for committing
        run: |
          git config --global user.name "${{ secrets.user_name }}"
          git config --global user.email "${{ secrets.user_email }}"

      # Step 5: Run the health check script
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./scripts/health-check.sh

      # Step 6: Commit and push health check logs via SSH
      - name: Commit health check logs
        run: |
          git add .
          git commit -m "[Automated] Update Health Check Logs"
          git push git@github.com:cypik/fettle.git HEAD:main
